# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ant',
                'doc_host': 'https://Fewsats.github.io',
                'git_url': 'https://github.com/Fewsats/ant',
                'lib_path': 'ant'},
  'syms': { 'ant.core': { 'ant.core.add_l402_tool': ('core.html#add_l402_tool', 'ant/core.py'),
                          'ant.core.create_func': ('core.html#create_func', 'ant/core.py'),
                          'ant.core.extract_function_code': ('core.html#extract_function_code', 'ant/core.py'),
                          'ant.core.generate_python_function': ('core.html#generate_python_function', 'ant/core.py'),
                          'ant.core.get_l402_uri_info': ('core.html#get_l402_uri_info', 'ant/core.py'),
                          'ant.core.get_text': ('core.html#get_text', 'ant/core.py')}}}
